### ISSUE TITLE
Bountiful 2.0.2 (1.17.1) server not starting

### ISSUE THREAD

**Issue by xllifi** [ejektaflex/Bountiful-Fabric#12]
Server log:
```
[05:39:09] [main/INFO]: Loading for game Minecraft 1.17.1
[05:39:09] [main/INFO]: [FabricLoader] Loading 116 mods:
	- antiqueatlas@6.1.1-fabric-mc1.17.1
	- apoli@2.0.5
	- appleskin@mc1.17-2.1.3
	- architectury@2.6.35
	- bountiful@2.0.2
	- calio@1.3.0
	- cardinal-components-base@3.1.1
	- cardinal-components-entity@3.1.1
	- cloth-basic-math@0.6.0
	- cloth-config2@5.1.40
	- comforts@0.0.7-1.17.1
	- controlling@1.1.2
	- cool_elytra@1.3.0
	- cosmetica@0.3.1
	- cozy_camping@1.0.0-1.17
	- dehydration@1.2.5
	- drinkbeer@2.3
	- dsurround@0.0.4
	- eatinganimationid@1.2
	- extraorigins@1.17-10
	- fabric@0.42.1+1.17
	- fabric-api-base@0.4.0+5847535018
	- fabric-api-lookup-api-v1@1.3.1+5847535018
	- fabric-biome-api-v1@3.2.2+5847535018
	- fabric-blockrenderlayer-v1@1.1.6+5847535018
	- fabric-command-api-v1@1.1.4+5847535018
	- fabric-commands-v0@0.2.3+5847535018
	- fabric-containers-v0@0.1.13+5847535018
	- fabric-content-registries-v0@0.3.1+5847535018
	- fabric-crash-report-info-v1@0.1.6+5847535018
	- fabric-dimensions-v1@2.0.13+5847535018
	- fabric-entity-events-v1@1.3.1+5847535018
	- fabric-events-interaction-v0@0.4.11+5847535018
	- fabric-events-lifecycle-v0@0.2.2+5847535018
	- fabric-game-rule-api-v1@1.0.8+5847535018
	- fabric-item-api-v1@1.2.5+5847535018
	- fabric-item-groups-v0@0.3.1+5847535018
	- fabric-key-binding-api-v1@1.0.5+5847535018
	- fabric-keybindings-v0@0.2.3+5847535018
	- fabric-language-kotlin@1.6.5+kotlin.1.5.31
	- fabric-lifecycle-events-v1@1.4.5+5847535018
	- fabric-loot-tables-v1@1.0.5+5847535018
	- fabric-mining-level-api-v1@1.0.2+6d0fac4218
	- fabric-mining-levels-v0@0.1.5+6d0fac4218
	- fabric-models-v0@0.3.1+5847535018
	- fabric-networking-api-v1@1.0.14+5847535018
	- fabric-networking-blockentity-v0@0.2.12+5847535018
	- fabric-networking-v0@0.3.3+5847535018
	- fabric-object-builder-api-v1@1.10.11+6d0fac4218
	- fabric-object-builders-v0@0.7.5+6d0fac4218
	- fabric-particles-v1@0.2.5+5847535018
	- fabric-registry-sync-v0@0.7.13+5847535018
	- fabric-renderer-api-v1@0.4.5+5847535018
	- fabric-renderer-indigo@0.4.9+5847535018
	- fabric-renderer-registries-v1@3.2.6+6d0fac4218
	- fabric-rendering-data-attachment-v1@0.1.6+5847535018
	- fabric-rendering-fluids-v1@0.2.1+6d0fac4218
	- fabric-rendering-v0@1.1.7+6d0fac4218
	- fabric-rendering-v1@1.10.1+6d0fac4218
	- fabric-resource-loader-v0@0.4.9+5847535018
	- fabric-screen-api-v1@1.0.5+5847535018
	- fabric-screen-handler-api-v1@1.1.9+5847535018
	- fabric-structure-api-v1@1.1.14+5847535018
	- fabric-tag-extensions-v0@1.2.2+5847535018
	- fabric-textures-v0@1.0.7+5847535018
	- fabric-tool-attribute-api-v1@1.3.1+eb76084f18
	- fabric-transfer-api-v1@1.5.1+6d0fac4218
	- fabricloader@0.11.7
	- fallflyinglib@3.0.0-beta.2
	- fallingleaves@1.7.4+1.17.1
	- fruitful@1.0.1
	- goosik-config@0.1.1
	- iris@1.1.2+build.9
	- itemscroller@0.15.0-dev.20210707.005506
	- java@16
	- kambrik@1.1.0
	- kanos_config@0.1.4+1.14.4-1.17.1
	- litematica@0.0.0-dev.20210906.183617
	- magic_mirror@1.3.2
	- malilib@0.10.0-dev.24
	- midnightlib@0.2.5
	- minecraft@1.17.1
	- modmenu@2.0.6
	- mostructures@1.3.0-pre1-1.17.1
	- nimble@1.0.0
	- notenoughcrashes@3.7.1+1.17.1
	- omega-config@1.0.8
	- org_jetbrains_kotlin_kotlin-reflect@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.31
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.2
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.3.0
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.3.0
	- org_openjdk_nashorn_nashorn-core@15.3
	- origins@1.1.4
	- origins-classes@1.2.2
	- pehkui@2.5.3+1.14.4-1.18
	- perspectivemod@0.0.5_01
	- physicsmod@2.5.17
	- plasmo_voice@1.0.12
	- playerabilitylib@1.3.0
	- reach-entity-attributes@2.1.1
	- roughlyenoughitems@6.2.333
	- seedy-behavior@1.0.2+1.17.1
	- shadeorigin@2.0
	- simple_backpack@1.1.19
	- skyvillages@1.0.0-fabric
	- smoothboot@1.16.5-1.6.0
	- sodium@0.3.2+IRIS2-build.9
	- somnus@0.0.13-1.17.1
	- terralith@1.6.1
	- visuality@0.3.2
	- worldedit@7.2.7+9f3e795
	- yee@1.0.0
[05:39:09] [main/WARN]: Mod `appleskin` (mc1.17-2.1.3) does not respect SemVer - comparison support is limited.
[05:39:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/egors/Downloads/sewrver/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[05:39:10] [main/INFO]: Compatibility level set to JAVA_16
[05:39:10] [main/WARN]: Reference map 'goosik-config-refmap.json' for goosik-config.mixins.json could not be read. If this is a development environment you can ignore this message
[05:39:11] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[05:39:11] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval)
[05:39:12] [main/INFO]: Kambrik Says Hello!
[05:39:12] [main/INFO]: Initializing StacktraceDeobfuscator
[05:39:12] [main/INFO]: Done initializing StacktraceDeobfuscator
[05:39:12] [main/INFO]: Smooth Boot config initialized
[05:39:19] [main/INFO]: Fruity!
[05:39:20] [main/INFO]: Apoli 2.0.5 has initialized. Ready to power up your game!
[05:39:20] [main/INFO]: Common init
[05:39:20] [main/INFO]: Origins 1.1.4 is initializing. Have fun!
[05:39:20] [main/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@3a63653b]
[05:39:20] [main/INFO]: WorldEdit for Fabric (version 7.2.7+9f3e795) is loaded
[05:39:23] [main/INFO]: Cozy Camping Blocks Registered!
[05:39:23] [main/INFO]: Cozy Camping Items Registered!
[05:39:23] [main/INFO]: Camper Point of Interest Registered!
[05:39:23] [main/INFO]: Camper Profession Registered!
[05:39:23] [main/INFO]: ATBYW Recipes Inintiliazed
[05:39:24] [main/INFO]: Cozy Camping Registered!
[05:39:24] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$znh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[05:39:24] [main/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[05:39:24] [main/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[05:39:24] [main/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[05:39:24] [main/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[05:39:24] [main/INFO]: Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[05:39:24] [main/INFO]: Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[05:39:24] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[05:39:25] [main/INFO]: Adding serverside commands..
[05:39:25] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
[05:39:25] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
[05:39:25] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
[05:39:25] [main/INFO]: [STDERR]: 	... 1 more
[05:39:25] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[05:39:25] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:39:25] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[05:39:25] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:39:25] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
[05:39:25] [main/INFO]: [STDERR]: 	... 2 more
[05:39:25] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
[05:39:25] [main/INFO]: [STDERR]: 	... 7 more
[05:39:25] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[05:39:25] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:39:25] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[05:39:25] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:39:25] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[05:39:25] [main/INFO]: [STDERR]: 	... 9 more
[05:39:25] [main/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodError: 'com.mojang.brigadier.Command io.ejekta.kambrik.command.KabrikCommandExtKt.kambrikCommand(kotlin.jvm.functions.Function1)'
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.bountiful.content.BountifulCommands.hand(BountifulCommands.kt:156)
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.bountiful.content.BountifulCommands.access$hand(BountifulCommands.kt:40)
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.bountiful.content.BountifulCommands$register$1$1.invoke(BountifulCommands.kt:72)
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.bountiful.content.BountifulCommands$register$1$1.invoke(BountifulCommands.kt:71)
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.kambrik.command.KambrikArgBuilder.literal(KambrikArgBuilder.kt:45)
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.kambrik.command.KambrikArgBuilder.invoke(KambrikArgBuilder.kt:110)
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.bountiful.content.BountifulCommands$register$1.invoke(BountifulCommands.kt:71)
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.bountiful.content.BountifulCommands$register$1.invoke(BountifulCommands.kt:46)
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.kambrik.command.KambrikCommandApi.addSourcedCommand$Kambrik(KambrikCommandApi.kt:58)
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.kambrik.command.KabrikCommandExtKt.addCommand(KabrikCommandExt.kt:24)
[05:39:25] [main/INFO]: [STDERR]: 	at io.ejekta.bountiful.content.BountifulCommands.register(BountifulCommands.kt:46)
[05:39:25] [main/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41)
[05:39:25] [main/INFO]: [STDERR]: 	at net.minecraft.class_2170.handler$zln000$fabric_addCommands(class_2170.java:1047)
[05:39:25] [main/INFO]: [STDERR]: 	at net.minecraft.class_2170.<init>(class_2170.java:235)
[05:39:25] [main/INFO]: [STDERR]: 	at net.minecraft.class_5350.<init>(class_5350.java:39)
[05:39:25] [main/INFO]: [STDERR]: 	at net.minecraft.class_5350.method_29466(class_5350.java:88)
[05:39:25] [main/INFO]: [STDERR]: 	at net.minecraft.server.Main.main(Main.java:147)
[05:39:25] [main/INFO]: [STDERR]: 	... 14 more

```

**Comment by ejektaflex** [comment]
It looks like you don't have the alpha version of Kambrik installed. 
https://www.curseforge.com/minecraft/mc-mods/kambrik/files/3533404
